ARG INSTALL_IMAGE_REF

FROM ${INSTALL_IMAGE_REF}
ARG INSTALL_IMAGE_REF
ENV INSTALL_IMAGE_REF=${INSTALL_IMAGE_REF}

# Copy the build script into the container
COPY iso/build_iso.sh /tmp/build_iso.sh

# Run the build script
RUN bash /tmp/build_iso.sh && rm -f /tmp/build_iso.sh
